### PR TITLE
Addition of curl 🔨

### PR DESCRIPTION
**Pull request by bserna-usgs**

### CODE REVIEW

**Comment by isuftin** [comment]
Might want it to look more like `Configure environment variable in $HOME/.bash_profile`

**Comment by bserna-usgs** [comment]
Just updated

**Comment by jmfee-usgs** [comment]
Please move cURL so it is in alphabetical order.  It also appears to support the generic `SSL_CERT_FILE` environment variable, but good to know about the curl specific variable.

**Comment by bserna-usgs** [comment]
Sorry I didn't notice there was an ordering

**Pull request merged**
