### PR TITLE
start to data science README

### PR DESCRIPTION
**Pull request by lindsaycarr**
Per the 2017 CDI Workshop, people are interested in starting conversations about Data Science at the USGS. We'd like to use GitHub issues and a README as a resource collection and directory tool.

### CODE REVIEW

**Comment by mguy-usgs** [comment]
Looks good to me. Only recommendation is to add a link to the datascience section from the main best-practices readme, maybe a new section...

**Comment by jmfee-usgs** [comment]
I think this looks good.  Not sure about the directory idea, since that may quickly fall out of date, but not necessarily opposed...

**Comment by emartinez-usgs** [comment]
I had previously created a "data" folder as a placeholder for potentially this type of information. Not sure on the intended difference between "data" and "data-science"?

I like the content ideas and general direction. I'm just not clear on the organization?

**Comment by lindsaycarr** [comment]
I think I heard someone recommend keeping the directory in CDI Confluence? I'm good with that.

per @emartinez-usgs question - data science differs from data (management) because it is the application of technology to data analysis, e.g. using python/R to create reproducible workflows for analyzing water quality trends. It's about the use of data, not necessarily management practices. There are a number other ways to define this, which is actually going to be a goal for discussing it here.

**Pull request merged**
