### PR TITLE
added guidelines that I have found helpful

### PR DESCRIPTION
**Pull request by jlant-usgs**

### CODE REVIEW

**Comment by emartinez-usgs** [comment]
Hey great contribution! As a rule I let pull requests for this project sit open for a comment period so I will do the same with this as well though I don't see anything controversial in here.

👍

**Comment by llastowka-usgs** [comment]
+1 Thank you!

**Comment by jlant-usgs** [comment]
That sounds good @emartinez-usgs.  You're welcome @llastowka-usgs.  I am happy to contribute.  This project is a great idea!

**Comment by mguy-usgs** [comment]
Nice additions. I appreciate the links to other sources as well.

**Pull request merged**
