### PR TITLE
Add notes for working within ssl intercept

### PR DESCRIPTION
**Pull request by jmfee-usgs**

### CODE REVIEW

**Comment by mhearne-usgs** [comment]
The Mac instructions worked for me. To get wget to work I had to add the instructions found at the link below.  Curl seemed to work without any extra configuration.

http://stackoverflow.com/questions/9224298/how-do-i-fix-certificate-errors-when-running-wget-on-an-https-url-in-cygwin

**Comment by jmfee-usgs** [comment]
For wget, the man page suggests the `--ca-certificate=` option, and combined with the environment configuration you could use
```
wget --ca-certificate=$SSL_CERT_FILE URL
```

**Comment by mhearne-usgs** [comment]
Yes, you could, but that would mean typing a bunch more characters every time I use wget, which seems much harder than setting it once and just typing "wget <url>".

**Comment by jmfee-usgs** [comment]
I normally use curl.  What about a wget alias?
```
alias wget="wget --ca-certificate=$SSL_CERT_FILE"
```

**Comment by jmfee-usgs** [comment]
I missed the part about using a `~/.wgetrc` file, seems reasonable...

**Pull request merged**
