### PR TITLE
make DOI Root cert instructions available to share

### PR DESCRIPTION
**Pull request by lindsaycarr**
We spend a lot of time emailing these instructions around, and wanted a canonical version somewhere. `best-practices` seemed like a good option!

### CODE REVIEW

**Comment by rsignell-usgs** [comment]
Thanks Lindsay!  I'm going to do one for python!

**Comment by cschroed-usgs** [comment]
Thanks Lindsay! To improve the discoverability of these sweet docs, you might consider adding a link to it from the main SSL intercept doc:
https://github.com/usgs/best-practices/blob/master/ssl/WorkingWithinSSLIntercept.md

**Comment by rsignell-usgs** [comment]
oops, I see that there is already some info in 
https://github.com/usgs/best-practices/blob/master/ssl/WorkingWithinSSLIntercept.md
about python.   

Maybe the R and Python info @lindsaycarr and I submitted should just beef up the info there?

**Comment by cschroed-usgs** [comment]
That's an option. I don't think there's a hard-and-fast rule about how were organizing this yet. Most SSL tricks are in the main SSL intercept page, but the Git-specific ones are in a separate doc. The rationale there was that the git tips were much longer than the other tips. Since the R tips are a little longer than the other snippets in the main doc, it might be reasonable to apply the same reasoning to make the R doc standalone.

**Comment by ldecicco-USGS** [comment]
If we want to beef it all into 1 file...first and foremost, we need some instructions for Windows users. I have literally no idea what is happening in that page.

**Comment by cschroed-usgs** [comment]
Good point @ldecicco-USGS !

**Comment by cschroed-usgs** [comment]
Created this to remind us to follow up:
https://github.com/usgs/best-practices/issues/63

**Pull request merged**
