### PR TITLE
adding more info on anaconda ssl

### PR DESCRIPTION
**Pull request by rsignell-usgs**

### CODE REVIEW

**Comment by jmfee-usgs** [comment]
As long as the referenced PEM file is a certificate bundle, and includes normal certificates in addition to the DOI intercept certificate, it should work without modification whether you are on network or off

**Comment by rsignell-usgs** [comment]
@jmfee-usgs, ah okay!

But the DOIRoot pem is the only file in my `$USERPROFILE\.certificates directory` 

Where would I find these "normal certificates" to put in there for making conda/anaconda work when not on TIC?

**Comment by jmfee-usgs** [comment]
One option is to download the mozilla certficate bundle from the CURL site:
https://curl.haxx.se/docs/caextract.html

Or there's a perl script that will generate from Mozilla's source repository:
https://github.com/curl/curl/blob/master/lib/mk-ca-bundle.pl


Once you have a certificate bundle (pem file with multiple certificates) you can append the DOI intercept certificate to the end of that file, and point anaconda to that one bundle.

**Comment by rsignell-usgs** [comment]
@jmfee-usgs , have you actually done this and have anaconda working both on and off TIC with no changes?

**Comment by jmfee-usgs** [comment]
Yes, I'm using a mac but anaconda is fairly consistent between platforms.

**Comment by cschroed-usgs** [comment]
It might not be relevant here, but I thought I would mention that Linux installations typically manage their CA cert bundle in pem format on disk. Distro-specific tools can be used to load the SSL Intercept root cert into the bundle. At that point, any tool that supports pem format CA cert bundles could rely on that file.  There are some details on Debian-specific and RedHat-derived distros [in the main SSL intercept page](https://github.com/usgs/best-practices/blob/master/ssl/WorkingWithinSSLIntercept.md#linux). So if you are running linux, you probably don't need to curate a separate CA cert bundle via https://curl.haxx.se/docs/caextract.html or https://github.com/curl/curl/blob/master/lib/mk-ca-bundle.pl .

It's a different story on Windows and macOS. Sorry I can't help too much there!

**Comment by rsignell-usgs** [comment]
@jmfee-usgs , okay, I can verify that this works on Windows:
* download this cert bundle: https://curl.haxx.se/ca/cacert.pem
* download the DOI cert: http://sslhelp.doi.net/docs/DOIRootCA2.cer
* open both files in a text editor and add the lines in `DOIRootCA2.cer` to the end of the lines in  `cacert.pem`. 
* save file as `<pathToYourFile>.pem`
* do `conda config --set ssl_verify <pathToYourFile>.pem`

Thanks!

**Comment by cschroed-usgs** [comment]
I think the discussion on merging the SSL Intercept root cert into an existing bundle is promising! I'm merging this as-is because it already looks pretty helpful, even without addressing cert bundle merging. If/when a concise cert bundle merging strategy emerges, it would be an awesome addition to this repo!

**Pull request merged**
